### ISSUE TITLE
Datepicker opens when scrolling on a touch device starts on the datepicker input

### ISSUE THREAD

**Issue by knitevision1** [nazar-pc/PickMeUp#101] opened 2015-12-27 03:22 UTC
Is there a way to fix that? I tried setting the toggler event to ``touchstart`` it made little help: the keyboard is not shown, but the datepicker is still visible.

**Comment by nazar-pc** [comment] 2015-12-27 05:12
Take a look at #91, please, looks like this is a duplicate of that.

**Comment by knitevision1** [comment] 2015-12-27 05:56
@nazar-pc This one uses a flat mode. What I am referring to is not described in the issue you linked.

Steps to reproduce what I mean:
1. Go to this page http://bit.ly/1ZuWuvk
2. Use the Chrome's Mobile Emulator or use the real device or using the Browserstack mobile devices
3. Try scrolling down with your finer starting to scroll on the input element

You'll see that the datepicker is opening.

Whilst the desired and expected behaviour would be this to be opened on click and not being opened when the user scrolls down.

**Comment by nazar-pc** [comment] 2015-12-27 06:00
Try to initialize datepicker with `trigger_event` option:
```js
$(..).pickmeup({
...
  trigger_event : 'click'
...
});
```

This should prevent datepicker from opening on touchstart.

**Closed** 2016-03-23 06:19 UTC
