### ISSUE TITLE
Some dates in october can't be selected

### ISSUE THREAD

**Issue by andrefpc** [nazar-pc/PickMeUp#180] opened 2017-08-28 14:07 UTC
Hello,

I tryed to use the plugin, but I found a little bug.

When i choose dates between 2017-10-16 and 2017-10-31, the background of date don't change and seems not mached.

I made a test on DEMO aplication, exposed in github, and the problem appears too.

**Comment by nazar-pc** [comment] 2017-08-28 16:28
Can you make a live demo?: https://github.com/nazar-pc/PickMeUp#contribution

**Comment by andrefpc** [comment] 2017-08-28 16:50
The problem occurs in your demo!

Try to select "2017-10-24", this date will not be selected.

**Comment by nazar-pc** [comment] 2017-08-28 16:53
Here on github and on jsfiddle works perfectly for me

**Comment by andrefpc** [comment] 2017-08-28 17:13
This is strange, because here a make tests in more than one browsers and the problem persists. Only for dates between  2017-10-16 and 2017-10-31!

**Comment by nazar-pc** [comment] 2017-08-28 17:14
Are you sure your OS is up to date?
Can't reproduce myself and I know no reason why it might not work properly.

**Comment by andrefpc** [comment] 2017-08-28 19:50
I'm sure.
The error are unexplainable, but occurs in my tests!

**Comment by rbferreyra** [comment] 2017-10-03 15:09
I make tests in demo page and the problem persists. Can you resolve that issue?

Tested in SO Linux Mint, Browser Google Chrome 61 and Firefox 55

**Comment by nazar-pc** [comment] 2017-10-03 15:19
I can't resolve issue that I can't reproduce, please help me to do this. I can select any date on any month in any mode without issues.
My OS is Ubuntu 17.10 x64 with all updates and browsers are Nightly builds of Firefox and Chromium.

1. In which mode (single date, range or multiple) you can't select date?
2. Can you record a screencast with this issue?
3. What exactly version of Linux Mint are you using (version and flavor, so that I can install exactly the same version in VM)? (and make sure you have all available updates are installed)
4. Also which timezone are you using?

**Comment by rbferreyra** [comment] 2017-10-03 15:37
1. All mode
2. https://drive.google.com/file/d/0B-VwjztxZq_BYnE1Wjc3RzRTZ3M/view
3. `RELEASE=18
CODENAME=sarah
EDITION="Xfce 64-bit"
DESCRIPTION="Linux Mint 18 Sarah"
DESKTOP=Xfce
TOOLKIT=GTK
NEW_FEATURES_URL=http://www.linuxmint.com/rel_sarah_xfce_whatsnew.php
RELEASE_NOTES_URL=http://www.linuxmint.com/rel_sarah_xfce.php
USER_GUIDE_URL=help:linuxmint
GRUB_TITLE=Linux Mint 18 Xfce 64-bit
`
4. Time zone: America/Sao_Paulo (BRT, -0300)

**Comment by sasknot** [comment] 2017-10-03 19:28
I'm having the same issue... I tried to log in line 508 of `pickmeup.js` and got this:

`console.log('111', _AAAAAA, options.date, val, day_element) (_AAAAAA means the 'if condition' down the line 508)`

15-10-2017
![screen shot 2017-10-03 at 16 18 02](https://user-images.githubusercontent.com/232754/31144625-b1785470-a857-11e7-8806-3d3e5fda44f3.png)

16-10-2017
![screen shot 2017-10-03 at 16 18 16](https://user-images.githubusercontent.com/232754/31144655-c2c0ad5e-a857-11e7-8631-6d23c0daa3bb.png)

17-10-2017
![screen shot 2017-10-03 at 16 18 24](https://user-images.githubusercontent.com/232754/31144670-ccad75c2-a857-11e7-8938-5ce6a8dd660a.png)


As you can see, when I click in 15-10-2017, `options.date` and `val` are equal, but when I click 16-10-2017 and 17-10-2017, they are different... I'm trying to debug more here to get solutions.

**Comment by sasknot** [comment] 2017-10-03 19:55
I think the problem is with Daylight Time... In Brazil we're going to add one hour, so from UTC-3 we're going to UTC-2... I think messes with the .valueOf() calculation

I added `local_date.setHours(0);` to line 477 from pickeup.js and it worked.

**Comment by nazar-pc** [comment] 2017-10-04 00:33
With your timezone I was able to reproduce an issue and I've just committed c6c8744d49eb074f378ed6c78d15720f673a0498 that is intended to fix it.
Test it, please, before I publish new release to NPM.

**Comment by nazar-pc** [comment] 2017-10-08 06:54
I've just released new version 3.0.9, it should fix the issue, let me know if you have other issue

**Closed by nazar-pc** 2017-10-08 06:54 UTC
Labels: bug
