### ISSUE TITLE
What to do if not just an input field

### ISSUE THREAD

**Issue by Supermanaco** [nazar-pc/PickMeUp#166] opened 2017-03-06 21:17 UTC
@nazar-pc ,
Sorry, I dont want to spam you.
PickMeUp works very good with only one input-field. But my form have a lot of input-fields. and now, it doesnt work. What shall i do? I think I have to use a classname, but I do not know how to do that. I would be very happy if you could help me.
Thanks so lot

**Comment by nazar-pc** [comment] 2017-03-06 21:19
This is basically a duplicate of #163, my comment from there should explain how to approach this task.

**Comment by Supermanaco** [comment] 2017-03-06 21:32
Many thanks, it works

**Comment by nazar-pc** [comment] 2017-03-06 21:34
Great to know!

**Closed by nazar-pc** 2017-03-06 21:34 UTC
Labels: question

**Comment by Supermanaco** [comment] 2017-03-06 21:37
And if i want to show only the number of events instead the events (the dates), because i want to hide the events (or the input-field with the events). my last question

**Comment by nazar-pc** [comment] 2017-03-06 21:40
You need to write some custom logic with [change event](https://github.com/nazar-pc/PickMeUp#pickmeup-change). Whenever selected dates change you can count how many dates were selected and use that information where you need.
