### ISSUE TITLE
No February if select_day : false

### ISSUE THREAD

**Issue by Cadaveri13** [nazar-pc/PickMeUp#113] opened 2016-03-30 15:01 UTC
I don't know what it is, but plugin sometimes just refuses to select february, and returns March instead.
As far as I can tell, it happens when select_day : false.

https://jsfiddle.net/Cadaveri13/z4fmvuzb/205/

**Comment by nazar-pc** [comment] 2016-04-18 06:58
Sorry for long delay. I can't reproduce this issue and "sometimes" is tricky.
Can you give me exact steps to reproduce bug so that I can fix i?

**Comment by Cadaveri13** [comment] 2016-04-18 14:41
It is tricky indeed, as far as I can tell it only happens when current month is March. Might be something with the number of days in the month, seeing that it only occurs with February and it's the only one that has 28 but idk.
This bug was present in the previosly posted fiddle, but dissapeared as soon as April hit. I know, sounds ridiculous.
Again, what happens is, with the options presented in the fiddle, I click on February, and input val is set to "2016-03".

**Comment by nazar-pc** [comment] 2016-04-18 23:51
Since it doesn't happen anymore and we can't reproduce it, let me close this for now.
We'll reopen this if it will start happening again.

**Closed by nazar-pc** 2016-04-18 23:51 UTC
